In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\shubham\.pyenv\pyenv-win\versions\3.10.0\python.exe -m pip install --upgrade pip' command.


In [4]:
#save dataframe or array values to text files also load them back
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]],np.int32)
np.savetxt('test.csv',x)

In [3]:
#loading file
y=np.loadtxt('test.txt')
print(y)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
