# Numpy

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: numpy in c:\users\shubham\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages (2.1.3)



You should consider upgrading via the 'c:\Users\shubham\.pyenv\pyenv-win\versions\3.10.0\python.exe -m pip install --upgrade pip' command.


# three main benefits that numpy array has over python list

1. Less memory
2. Fast
3. Convenient

In [ ]:
#Less memory

import sys
import numpy as np

l=range(1000)
print(sys.getsizeof(10)*len(l))


array=np.arange(1000)
print(array.size*array.itemsize)

28000
8000


In [5]:
#Fast

import time
import numpy as np

SIZE=1000000

l1=range(SIZE)#[0,1,2,3...]    [(0,0),(1,1),(2,2),(3,3)....]
l2=range(SIZE)#[0,1,2,3....]

a1=np.arange(SIZE)
a2=np.arange(SIZE)

start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("python list took:",(time.time()-start)*1000)


start=time.time()
result=a1+a2
print("numpy took:",(time.time()-start)*1000)

python list took: 169.8760986328125
numpy took: 18.08929443359375


list----->10101345----->989735------>pointers
numpy --->12
            13
            14
            15

In [6]:
import numpy as np
print(np.array([1,2,3]))

[1 2 3]


In [7]:
print(np.array([[1,2,3],[4,5,6]]))

[[1 2 3]
 [4 5 6]]


In [8]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
import numpy as np
a=np.array([1,2,3]) #one dimensional array
print(a[1])
print(a.ndim)


2
1


In [ ]:
b=np.array([[1,2,3],[4,5,6]]) #two dimensional array
print(b.ndim)
print(b.itemsize)

2
8
