In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\shubham\.pyenv\pyenv-win\versions\3.10.0\python.exe -m pip install --upgrade pip' command.


In [4]:
import numpy as np
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [5]:
a[1,2]

np.int64(3)

In [6]:
a[0:2,2]

array([8, 3])

In [7]:
a[-1,0:2]

array([9, 3])

In [8]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [9]:
#iterating through a matrix
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [10]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [11]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [12]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [14]:
#vertical stacking
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
#horizontal stacking
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [16]:
a=np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [17]:
#hsplit and vsplit
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [18]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [19]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
b=a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [22]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])